[tox]
envlist = py310, py311, py312, py313
isolated_build = True

[testenv]
deps =
    -r requirements.txt
    -r dev-requirements.txt

commands =
    pytest -v -o junit_family=xunit1 --cov=. --cov-report xml:coverage.xml --cov-report html:test-results/cov_html --junitxml=xunit-reports/xunit.xml
    pylint licensetool/licensetool/*.py tests/*.py

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test
python_functions = test_*

[coverage:run]
source = licensetool
branch = True

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if __name__ == .__main__.:
