name: PR-check
run-name: ${{ github.actor }} PR checker
on:
  push:
  workflow_dispatch:
jobs:
  run-pytest-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y build-essential python3-pandas
      - run: pip install -r requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: pip install --editable .
      - run: pytest -v -o junit_family=xunit1 --cov=. --cov-report xml:coverage.xml --cov-report html:test-results/cov_html --junitxml=xunit-reports/xunit.xml
      - run: pylint licensetool.py tests/*.py
